# Generated by Django 2.1.7 on 2019-03-02 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_logo', models.ImageField(upload_to='organizations/logos/%Y/%m/%d')),
                ('organization_name', models.CharField(max_length=100)),
                ('about_organization', models.TextField()),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('required_funding', models.IntegerField()),
                ('total_amount', models.CharField(max_length=25)),
                ('impact', models.TextField()),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('resources_providing', models.TextField(blank=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
